apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer #ClusterIp
  selector:
    app: httpd # it should be same as the pod 
  ports:
   
    - #nodePort: 31000 # port of EC2 #node port #its not needed when there is a ingress controller dealing , no need to talk with directly on node port 
      port: 80 #service port  
      targetPort: 80 #target port 

